name: Release package

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write  # Required for OIDC
  contents: write
  issues: write # Required for raising isdues

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
    
      - name: Use Node.js 22.x
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: 'npm'
      
      - run: npm version ${{ github.ref_name }} --no-git-tag-version

      - run: npm install

      - run: npm test

      - run: npm pack

      - name: NPM Publish
        id: publish
        run: npm publish

      - name: Create issue on npm publish failure
        if: ${{ steps.publish.outcome == 'failure' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue create \
            --title "NPM Publish step failed for release ${GITHUB_REF_NAME}" \
            --body "The NPM publish step failed for release: ${GITHUB_REF_NAME}. The npm package will need to be manually uploaded to NPM.
            --assignee AndrewSouthpaw
        
      - name: Release
        if: ${{ always() }}
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            ./anchor-markdown-header-*.tgz
